baseURL = 'ilan-w.github.io/docs'
languageCode = 'en-us'
publishDir = 'docs'
title = 'yilan'
#theme = 'ananke'
theme = 'hugo-book'
#theme = 'hugo-theme-shell'


[params]
BookTheme = 'auto'
BookLogo = 'logo.png'
